### ISSUE TITLE
[Ошибка] TgCrypto is missing! ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'

### ISSUE THREAD

**Issue by ButCheR-PRO** [Alexell/MuskEmpireBot#1]
```
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
Traceback (most recent call last):
  File "D:\Crypto\MuskEmpireBot-main\main.py", line 2, in <module>
    from bot.core import launcher
  File "D:\Crypto\MuskEmpireBot-main\bot\core\launcher.py", line 7, in <module>
    from better_proxy import Proxy
  File "D:\Crypto\MuskEmpireBot-main\venv\lib\site-packages\better_proxy\__init__.py", line 1, in <module>
    from .proxy import Proxy, parse_proxy_str
  File "D:\Crypto\MuskEmpireBot-main\venv\lib\site-packages\better_proxy\proxy.py", line 5, in <module>
    from pydantic import BaseModel
  File "D:\Crypto\MuskEmpireBot-main\venv\lib\site-packages\pydantic\__init__.py", line 404, in __getattr__
    module = import_module(module_name, package=package)
  File "C:\Users\RooT\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\Crypto\MuskEmpireBot-main\venv\lib\site-packages\pydantic\main.py", line 27, in <module>
    import pydantic_core
  File "D:\Crypto\MuskEmpireBot-main\venv\lib\site-packages\pydantic_core\__init__.py", line 6, in <module>
    from ._pydantic_core import (
ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'
Для продолжения нажмите любую клавишу . . .

```

Python 3.10.9
Пробовал 
```
pip install pydantic_core
pip install TgCrypto
```
но пишет что уже установлено

**Comment by Alexell** [comment]
Следуйте инструкции по установке и устанавливайте в виртуальном окружении pip install -r requirements.txt, чтобы не было конфликтов с другими проектами и их зависимостями.
