### ISSUE TITLE
error

### ISSUE THREAD

**Issue by threedoubleo** [Alexell/MuskEmpireBot#7]
Traceback (most recent call last):
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python312\Lib\zoneinfo\_common.py", line 12, in load_tzdata
    return resources.files(package_name).joinpath(resource_name).open("rb")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python312\Lib\importlib\resources\_common.py", line 46, in wrapper
    return func(anchor)
           ^^^^^^^^^^^^
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python312\Lib\importlib\resources\_common.py", line 56, in files
    return from_package(resolve(anchor))
                        ^^^^^^^^^^^^^^^
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python312\Lib\functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python312\Lib\importlib\resources\_common.py", line 82, in _
    return importlib.import_module(cand)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tzdata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sergey\Desktop\BOTS\MuskEmpireBot\main.py", line 11, in <module>
    asyncio.run(main())
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Sergey\Desktop\BOTS\MuskEmpireBot\main.py", line 6, in main
    await launcher.start()
  File "C:\Users\Sergey\Desktop\BOTS\MuskEmpireBot\bot\core\launcher.py", line 106, in start
    await run_clients(tg_clients=tg_clients)
  File "C:\Users\Sergey\Desktop\BOTS\MuskEmpireBot\bot\core\launcher.py", line 82, in run_clients
    await asyncio.gather(*tasks)
  File "C:\Users\Sergey\Desktop\BOTS\MuskEmpireBot\bot\core\launcher.py", line 69, in run_bot_with_delay
    await run_bot(tg_client=tg_client, proxy=proxy)
  File "C:\Users\Sergey\Desktop\BOTS\MuskEmpireBot\bot\core\bot.py", line 516, in run_bot
    await CryptoBot(tg_client=tg_client).run(proxy=proxy)
  File "C:\Users\Sergey\Desktop\BOTS\MuskEmpireBot\bot\core\bot.py", line 388, in run
    gmt_timezone = ZoneInfo('GMT')
                   ^^^^^^^^^^^^^^^
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python312\Lib\zoneinfo\_common.py", line 24, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key GMT'

**Comment by Alexell** [comment]
I do not guarantee that the bot will work on Python versions other than 3.10. Try installing the module: `pip install tzdata`

**Comment by Alexell** [comment]
It seems in Python 3.12 and newer, zoneinfo relies on external data from the tzdata package, while Python 3.10 does not require tzdata.
